name: ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn
        working-directory: ./web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}
          CI: true

      - name: Check types
        run: yarn type
        working-directory: ./web

      - name: Tests
        run: yarn test
        working-directory: ./web

      - name: Build
        run: yarn build
        working-directory: ./web
